import { generateContent } from "../../utils/llm.js";
import { getConversationHistory, appendToMemory } from "../../utils/memory.js";
import { cleanResponse } from "../../utils/cleanResponse.js";
import {
  extractCodeBlocks,
  classifyCodeResponse,
  buildPreviewHtml,
  fileNameForType,
} from "../../utils/codePreview.js";
import { saveArtifact, createArtifact } from "../../utils/artifactStore.js";
import { runCode } from "../../utils/runCode.js";

const SYSTEM_PROMPT = `You are Nexus AI's Senior Software Engineer and Coding Specialist.
Provide clean, robust, well-commented, and production-ready code.
Use proper Markdown code fences with language tags (e.g. \`\`\`html, \`\`\`css,
\`\`\`javascript, \`\`\`python).
For UI requests (webpage/calculator/dashboard/etc.), provide the complete
HTML/CSS/JavaScript (or React JSX) needed to render a working app.
Keep explanations concise, crisp, and focused on implementation best practices.`;

const WEB_UI_DETECT =
  /\b(html|css|react|jsx|webpage|web page|website|web app|landing ?page|calculator|dashboard|todo|portfolio|interface|frontend|game|animation|ui)\b/i;

/** Build a self-contained HTML fallback for web-UI requests (no LLM needed). */
function buildWebFallback(prompt) {
  const title = (prompt || "Web App").slice(0, 60);
  const safeTitle = title.replace(/"/g, "'");
  return `### Web App Generated Offline

Here is a functional HTML/CSS/JS implementation for **"${safeTitle}"** (generated from fallback templates while the language model is unavailable):

\`\`\`html
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${safeTitle}</title>
<style>
  :root { color-scheme: light dark; }
  * { box-sizing: border-box; font-family: system-ui, sans-serif; }
  body { margin: 0; min-height: 100vh; display: flex; align-items: center; justify-content: center;
         background: linear-gradient(135deg, #0f172a, #312e81); color: #e2e8f0; padding: 20px; }
  .card { background: rgba(255,255,255,0.06); border: 1px solid rgba(255,255,255,0.15);
          border-radius: 16px; padding: 28px; max-width: 420px; width: 100%; text-align: center;
          box-shadow: 0 20px 50px rgba(0,0,0,0.4); backdrop-filter: blur(8px); }
  h1 { font-size: 1.4rem; margin: 0 0 10px; }
  p { color: #94a3b8; font-size: 0.95rem; margin: 0 0 18px; }
  .output { font-size: 2rem; font-weight: 700; margin: 12px 0 18px; color: #a5b4fc; min-height: 2.4rem; }
  button { cursor: pointer; padding: 10px 18px; border-radius: 10px; border: 0;
           background: #6366f1; color: #fff; font-weight: 600; transition: transform .1s; }
  button:hover { background: #818cf8; } button:active { transform: scale(0.96); }
  .foot { margin-top: 16px; font-size: 0.7rem; color: #64748b; }
</style>
</head>
<body>
  <div class="card">
    <h1>${safeTitle}</h1>
    <p>A working preview generated by Nexus AI. Interact with the button below.</p>
    <div class="output" id="output">0</div>
    <button id="btn">Click me</button>
    <div class="foot">Nexus AI \u00b7 Live Preview</div>
  </div>
  <script>
    const output = document.getElementById('output');
    const btn = document.getElementById('btn');
    let count = 0;
    btn.addEventListener('click', () => {
      count += 1;
      output.textContent = count;
    });
  <\/script>
</body>
</html>
\`\`\`

> While the online model is rate-limited, this fallback still gives you a real, editable implementation and live preview. Retry your prompt shortly to get a fully custom build.`;
}

export async function codingNode(state) {
  console.log(`[Coding Agent] Generating code solution for: "${state.prompt}"`);

  let artifact = null;
  let finalOutput = "";

  try {
    const history = await getConversationHistory(state.conversationId);
    let llmResponse = await generateContent({
      systemPrompt: SYSTEM_PROMPT,
      prompt: state.prompt,
      history,
      temperature: 0.2,
    });

    if (llmResponse) {
      finalOutput = cleanResponse(llmResponse);
    } else if (WEB_UI_DETECT.test(state.prompt)) {
      // LLM unavailable (e.g. rate limited) → still deliver a real, previewable UI.
      finalOutput = buildWebFallback(state.prompt);
    } else {
      finalOutput = `### Code Solution\n\nHere is the implementation for **"${state.prompt}"**:\n\n\`\`\`python\ndef solution():\n    """Implementation for ${state.prompt}"""\n    print("Nexus AI Code Execution")\n    return True\n\nif __name__ == "__main__":\n    solution()\n\`\`\``;
    }

    const blocks = extractCodeBlocks(finalOutput);
    const classification = classifyCodeResponse(state.prompt, blocks);

    console.log(
      `[Coding Agent] ${blocks.length} code block(s), preview=${classification.previewType}`
    );

    if (classification.previewType === "iframe" && blocks.length > 0) {
      // Build a sandbox-ready HTML preview and store it as an artifact.
      const previewHtml = buildPreviewHtml({
        blocks,
        language: classification.language,
      });

      const stored = await saveArtifact({
        data: Buffer.from(previewHtml, "utf-8"),
        filename: `nexus-preview-${Date.now()}.html`,
        mimeType: "text/html",
      });

      artifact = createArtifact({
        artifactType: "html",
        name: stored.name,
        mimeType: stored.mimeType,
        url: stored.url,
        previewType: "iframe",
        metadata: {
          language: classification.language,
          files: blocks.map((b) => ({ language: b.language, filename: b.filename })),
          code: blocks.map((b) => ({ language: b.language, content: b.code })),
          generatedAt: new Date().toISOString(),
        },
      });
    } else {
      // Source code artifact (no browser execution available/requested).
      artifact = createArtifact({
        artifactType: "code",
        name:
          blocks.length > 0
            ? fileNameForType("code", Date.now())
            : "source.txt",
        mimeType: "text/plain",
        url: null, // no stored file — source stays inline
        previewType: "code",
        metadata: {
          language: classification.language,
          files: blocks.map((b) => ({ language: b.language, filename: b.filename })),
          code: blocks.map((b) => ({ language: b.language, content: b.code })),
          generatedAt: new Date().toISOString(),
        },
      });

      // Optional server-side execution for Python/JS when enabled.
      if (blocks.length === 1 && ["python", "py", "javascript", "js"].includes(blocks[0].language)) {
        const execResult = await runCode({
          language: blocks[0].language,
          code: blocks[0].code,
        });
        artifact.metadata.execution = execResult;
        if (execResult.executed) {
          finalOutput += `\n\n### Execution Output\n\n\`\`\`\n${execResult.stdout || "(no output)"}${execResult.stderr ? `\n\n[stderr]\n${execResult.stderr}` : ""}\n\`\`\``;
        }
      }
    }
  } catch (error) {
    console.error(`[Coding Agent] Unexpected error: ${error.message}`);
    finalOutput = `### Code Generation Failed\n\nI couldn't generate that code due to an internal error. Please try again.`;
  }

  if (state.conversationId) {
    await appendToMemory(state.conversationId, "user", state.prompt);
    await appendToMemory(state.conversationId, "assistant", finalOutput);
  }

  return {
    output: finalOutput,
    artifact,
    messages: [
      {
        role: "assistant",
        sender: "Coding Agent",
        content: finalOutput,
      },
    ],
  };
}