import { generateContent } from "../../utils/llm.js";
import { generateStructuredJson } from "../../utils/structuredLlm.js";
import { generatePdfBuffer } from "../../utils/pdfGen.js";
import { saveArtifact, createArtifact } from "../../utils/artifactStore.js";
import { getConversationHistory, appendToMemory } from "../../utils/memory.js";
import { cleanResponse } from "../../utils/cleanResponse.js";

const SYSTEM_PROMPT = `You are Nexus AI's Document and PDF Specialist.
Generate detailed, well-structured Markdown content for a professional report
based on the user's request. Use:
- One H1 title
- H2/H3 section headings
- Bullet points, tables, and short paragraphs
- A concluding section

Output ONLY the markdown document content. Do not describe the process.`;

const TITLE_EXTRACTOR = `Extract a short document title (max 8 words) from this PDF request.
Return ONLY a JSON object: {"title": "..."}`;

export async function pdfNode(state) {
  console.log(`[PDF Agent] Generating real PDF for: "${state.prompt}"`);

  let artifact = null;
  let finalOutput = `### PDF Generation\n\nGenerating a PDF document for **"${state.prompt}"**...`;

  try {
    const history = await getConversationHistory(state.conversationId);

    let markdown = await generateContent({
      systemPrompt: SYSTEM_PROMPT,
      prompt: state.prompt,
      history,
      temperature: 0.4,
    });

    if (!markdown) {
      // Resilient fallback blueprint so a real PDF is still produced.
      markdown = `# ${state.prompt}\n\n## Overview\nAutomated report generated by Nexus AI for **"${state.prompt}"**.\n\n## Key Sections\n- Executive summary\n- Detailed analysis\n- Data and findings\n- Recommendations\n\n## Conclusion\nThis document was generated on demand by the Nexus AI PDF Agent.`;
    }

    const titleJson = await generateStructuredJson({
      systemPrompt: TITLE_EXTRACTOR,
      prompt: state.prompt,
      history,
      temperature: 0.2,
      maxOutputTokens: 64,
    });
    const title = titleJson?.title || state.prompt.slice(0, 60);

    const { buffer, pageCount } = await generatePdfBuffer(markdown);

    const stored = await saveArtifact({
      data: buffer,
      filename: `nexus-doc-${Date.now()}.pdf`,
      mimeType: "application/pdf",
    });

    artifact = createArtifact({
      artifactType: "pdf",
      name: stored.name,
      mimeType: stored.mimeType,
      url: stored.url,
      previewType: "pdf",
      metadata: {
        title,
        pageCount,
        generatedAt: new Date().toISOString(),
      },
    });

    const clean = cleanResponse(markdown);
    finalOutput = `### PDF Report Ready\n\nThe document **"${title}"** has been generated (${pageCount} page${pageCount === 1 ? "" : "s"}).\n\n${clean.length > 1200 ? clean.slice(0, 1200) + "\n\n…" : clean}`;
    console.log(`[PDF Agent] Artifact stored: ${stored.name} (${pageCount} pages)`);
  } catch (error) {
    console.error(`[PDF Agent] Generation failed: ${error.message}`);
    finalOutput = `### PDF Generation Failed\n\nI couldn't produce a valid PDF file right now.\n\n**Reason:** ${error.message || "Unknown error"}`;
  }

  if (state.conversationId) {
    await appendToMemory(state.conversationId, "user", state.prompt);
    await appendToMemory(state.conversationId, "assistant", finalOutput);
  }

  return {
    output: finalOutput,
    artifact,
    messages: [
      {
        role: "assistant",
        sender: "PDF Agent",
        content: finalOutput,
      },
    ],
  };
}