import { generateStructuredJson } from "../../utils/structuredLlm.js";
import { generatePptxBuffer } from "../../utils/pptGen.js";
import { saveArtifact, createArtifact } from "../../utils/artifactStore.js";
import { getConversationHistory, appendToMemory } from "../../utils/memory.js";

const MIN_SLIDES = 6;
const MAX_SLIDES = 10;

/** If the user asked for an explicit slide count ("5-slide deck"), honor it. */
function requestedSlideCount(prompt) {
  const m = /\b(\d{1,2})\s*(-\s*)?slides?\b/i.exec(prompt || "");
  if (!m) return null;
  const n = parseInt(m[1], 10);
  return Math.min(12, Math.max(3, n));
}

function slideCountRule(minSlides, maxSlides) {
  return minSlides === maxSlides
    ? `exactly ${minSlides} slides total. The user explicitly asked for ${minSlides} slides.`
    : `between ${minSlides} and ${maxSlides} slides total (never fewer, never more).`;
}

function buildSystemPrompt(minSlides, maxSlides) {
  return `You are Nexus AI's Presentation & Slide Architect.
Design a professional, visually-driven slide deck on the topic the user asks for.

Deck structure rules:
- The deck MUST contain ${slideCountRule(minSlides, maxSlides)}
- Slide 1: title slide -> give it a "subtitle" field (a one-line tagline) and no bullets.
- Slide 2: agenda -> 4-6 short bullets listing what the deck covers.
- Middle slides: 4-7 content slides that cover the topic IN DEPTH (definitions,
  how it works, benefits, challenges, real-world examples, data/trends, comparison,
  recommendations - as relevant to the topic).
- Final slide: conclusion / call-to-action.

Content quality rules:
- Every bullet must be a complete, information-rich sentence with concrete facts,
  examples, mechanisms or numbers - never vague labels like "Overview" or "Points".
- 3-6 bullets per content slide.
- Write a 1-2 sentence speaker note for EVERY slide.
- Stay strictly on the user's topic; every slide must be specific to it.
- Latin characters only; no emoji or special symbols.

Return ONLY a strict JSON array in this exact shape — no markdown, no commentary:

[
  {"title": "Slide title", "subtitle": "tagline (title slide only)", "bullets": ["bullet one", "bullet two"], "notes": "speaker note"}
]`;
}

const FALLBACK_DECK = [
  {
    title: "PPTX: An Overview",
    subtitle: "A briefing generated by Nexus AI",
    bullets: [],
    notes: "Welcome the audience and introduce the topic.",
  },
  {
    title: "Agenda",
    bullets: ["Introduction and background", "Core concepts explained", "Analysis and examples", "Challenges and opportunities", "Recommendations", "Conclusion and next steps"],
    notes: "Walk through what the deck will cover.",
  },
  {
    title: "Background & Context",
    bullets: [`What "${"PPTX"}" means and why it matters`, "How it has evolved recently", "Who is affected by it"],
    notes: "Set the scene for the audience.",
  },
  {
    title: "Core Analysis",
    bullets: ["Primary drivers and trends", "Concrete examples and evidence", "Comparison with alternatives"],
    notes: "Highlight the main findings.",
  },
  {
    title: "Recommendations",
    bullets: ["Actionable next steps", "Measurable milestones", "Owners and timelines"],
    notes: "Detail the recommended path forward.",
  },
  {
    title: "Conclusion & Next Steps",
    bullets: ["Summary of the key points", "What to do next", "Thank you and Q&A"],
    notes: "Wrap up and invite questions.",
  },
];

/** Topical slides used to top the deck up to the 6-slide minimum. */
const PAD_SLIDE_TEMPLATES = (topic) => [
  {
    title: "Key Takeaways",
    bullets: [`The single most important insight about ${topic}`, "Supporting evidence and real-world examples", "Why this matters right now"],
    notes: "Reinforce the core message of the deck.",
  },
  {
    title: "Challenges & Mitigations",
    bullets: [`Main obstacles around ${topic}`, "Practical mitigation strategies", "Risks to monitor over time"],
    notes: "Be honest about the difficulties and how to handle them.",
  },
  {
    title: "Roadmap & Next Steps",
    bullets: ["Short-term actions to take immediately", "Medium-term milestones to aim for", "How to measure success"],
    notes: "Give the audience something concrete to act on.",
  },
  {
    title: "Thank You & Q&A",
    bullets: ["Questions and open discussion", "Follow-up resources and contact"],
    notes: "Invite questions and thank the audience.",
  },
];

/** Normalize a raw slide object from the LLM into a safe, consistent shape. */
function normalizeSlide(raw) {
  const s = raw || {};
  return {
    title: String(s.title || "").replace(/\s+/g, " ").trim().slice(0, 70) || "Untitled Slide",
    subtitle: s.subtitle ? String(s.subtitle).replace(/\s+/g, " ").trim().slice(0, 120) : "",
    bullets: (Array.isArray(s.bullets) ? s.bullets : [])
      .map((b) => String(b).replace(/\s+/g, " ").trim())
      .filter(Boolean)
      .slice(0, 6),
    notes: String(s.notes || "").trim().slice(0, 500),
  };
}

export async function pptNode(state) {
  console.log(`[PPT Agent] Generating real .pptx for: "${state.prompt}"`);

  let artifact = null;
  let finalOutput = `### Presentation Generation\n\nBuilding a PowerPoint deck for **"${state.prompt}"**...`;

  try {
    const history = await getConversationHistory(state.conversationId);

    // Honor an explicit count from the user ("5-slide deck"), else default 6-10.
    const requested = requestedSlideCount(state.prompt);
    const minSlides = requested ?? MIN_SLIDES;
    const maxSlides = requested ?? MAX_SLIDES;

    const countInstruction = `Produce ${slideCountRule(minSlides, maxSlides)}`;

    let raw = await generateStructuredJson({
      systemPrompt: buildSystemPrompt(minSlides, maxSlides),
      prompt: `Create a presentation about: ${state.prompt}\n\n${countInstruction} Cover this specific topic in depth and follow all structure rules.`,
      history,
      temperature: 0.6,
      maxOutputTokens: 6000,
    });

    // Single resilience retry when the model does not return a usable array.
    if (!Array.isArray(raw) || !raw.some((s) => s && (s.title || s.bullets))) {
      console.warn("[PPT Agent] First pass returned invalid JSON; retrying once.");
      raw = await generateStructuredJson({
        systemPrompt:
          buildSystemPrompt(minSlides, maxSlides) +
          "\n\nThe previous attempt was invalid. Respond with ONLY the strict JSON array — no prose, no markdown.",
        prompt: `Create a presentation about: ${state.prompt}\n\n${countInstruction} Cover this specific topic in depth and follow all structure rules.`,
        history: [],
        temperature: 0.3,
        maxOutputTokens: 6000,
      });
    }

    // Some models wrap the array in an object: { "slides": [...] }
    if (raw && !Array.isArray(raw) && Array.isArray(raw.slides)) {
      raw = raw.slides;
    }

    let slides = Array.isArray(raw)
      ? raw
          .map(normalizeSlide)
          // Keep slides that have content; the title slide is valid with only
          // a subtitle and no bullets. Drop truly empty slides.
          .filter((s) => s.title && (s.bullets.length > 0 || s.subtitle))
      : [];

    if (slides.length === 0) {
      console.warn("[PPT Agent] LLM returned invalid deck, using fallback.");
      slides = FALLBACK_DECK.map((s) => ({
        ...normalizeSlide(s),
        title: s.title.replace("PPTX", state.prompt),
      }));
    }

    // Enforce the requested slide window: hard cap, then top up to the minimum.
    slides = slides.slice(0, maxSlides);
    if (slides.length < minSlides) {
      const pads = PAD_SLIDE_TEMPLATES(state.prompt).filter(
        (p) => !slides.some((s) => s.title.toLowerCase() === p.title.toLowerCase())
      );
      slides = slides.concat(pads.slice(0, minSlides - slides.length));
      console.log(`[PPT Agent] Deck topped up to ${slides.length} slides (min ${minSlides}).`);
    }

    const { buffer, slideCount } = await generatePptxBuffer(slides);

    const stored = await saveArtifact({
      data: buffer,
      filename: `nexus-deck-${Date.now()}.pptx`,
      mimeType:
        "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    });

    artifact = createArtifact({
      artifactType: "pptx",
      name: stored.name,
      mimeType: stored.mimeType,
      url: stored.url,
      previewType: "slides",
      metadata: {
        slideCount,
        slides,
        title: slides[0]?.title || state.prompt,
        generatedAt: new Date().toISOString(),
      },
    });

    finalOutput = `### Presentation Ready\n\nYour PowerPoint deck **"${slides[0]?.title || "Untitled"}"** has been generated with **${slideCount} slides**.\n\nPreview the slides above, or use the *Open* / *Download* actions to access the .pptx file.`;
    console.log(`[PPT Agent] Artifact stored: ${stored.name} (${slideCount} slides)`);
  } catch (error) {
    console.error(`[PPT Agent] Generation failed: ${error.message}`);
    finalOutput = `### Presentation Generation Failed\n\nI couldn't produce the PowerPoint deck right now.\n\n**Reason:** ${error.message || "Unknown error"}`;
  }

  if (state.conversationId) {
    await appendToMemory(state.conversationId, "user", state.prompt);
    await appendToMemory(state.conversationId, "assistant", finalOutput);
  }

  return {
    output: finalOutput,
    artifact,
    messages: [
      {
        role: "assistant",
        sender: "PPT Agent",
        content: finalOutput,
      },
    ],
  };
}